In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.rand([8, 100, 10]).detach()
x

tensor([[[4.7901e-01, 7.5752e-01, 6.8014e-01,  ..., 8.4620e-01,
          2.1694e-02, 5.4258e-01],
         [7.8639e-01, 5.9219e-01, 1.7673e-01,  ..., 7.3143e-01,
          9.5931e-01, 8.2458e-01],
         [4.7521e-01, 5.0097e-01, 8.4320e-01,  ..., 6.9292e-01,
          6.4552e-04, 2.1447e-02],
         ...,
         [2.5530e-01, 4.6809e-01, 3.9989e-01,  ..., 2.9638e-01,
          3.7990e-01, 8.6260e-01],
         [7.6159e-01, 3.1584e-01, 4.9473e-01,  ..., 6.8497e-01,
          3.4244e-01, 7.3588e-01],
         [2.0436e-01, 4.2053e-01, 7.2203e-01,  ..., 7.8613e-01,
          3.3993e-01, 2.3390e-01]],

        [[1.1662e-02, 4.4464e-02, 1.8670e-01,  ..., 3.9988e-01,
          9.7095e-01, 4.6521e-01],
         [4.4582e-01, 3.2129e-01, 5.4050e-01,  ..., 6.8167e-01,
          6.5012e-01, 9.0964e-01],
         [1.5230e-01, 7.2412e-01, 3.6466e-01,  ..., 4.9376e-01,
          2.3578e-01, 6.6712e-01],
         ...,
         [5.8602e-01, 6.3257e-01, 4.3618e-01,  ..., 3.9502e-01,
          2.973

In [3]:
y = torch.rand(8)
y = (y > 0.5).int()
y

tensor([0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)

In [4]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.first_layer = nn.Linear(1000, 50)
        self.second_layer = nn.Linear(50, 1)

    def forward(self, x):
        x = torch.flatten(x, start_dim=1, end_dim=2)
        x = nn.functional.relu(self.first_layer(x))
        x = self.second_layer(x)
        return x

In [5]:
mlp= MLP()
output = mlp(x)

In [6]:
output

tensor([[0.1486],
        [0.1711],
        [0.0181],
        [0.1344],
        [0.0982],
        [0.0463],
        [0.1445],
        [0.0676]], grad_fn=<AddmmBackward0>)

In [7]:
class Embedding(nn.Module):
    def __init__(self):
        super(Embedding, self).__init__()
        self.embedding = nn.Embedding(4, 100)

    def forward(self, x):
        return self.embedding(x)

In [8]:
embedding = Embedding()

embedding_input = torch.tensor([[0, 1, 0], [2, 3, 3]])
embedding_output = embedding(embedding_input)

In [9]:
embedding_output.shape

torch.Size([2, 3, 100])

In [13]:
class LSTM(nn.Module):
    def __init__(self):
        super(LSTM, self).__init__()
        self.lstm = nn.LSTM(10, 15, num_layers=2, bidirectional=True, dropout=0.1)

    def forward(self, x):
        output, (hidden, cell) = self.lstm(x)
        return output, hidden, cell

In [14]:
permute_x = x.permute([1, 0, 2])
lstm = LSTM()
output_lstm1, output_lstm2, output_lstm3 = lstm(permute_x)

In [15]:
output_lstm1

tensor([[[ 0.0217, -0.0607, -0.0139,  ...,  0.0726,  0.1714,  0.0123],
         [-0.0029, -0.0445,  0.0026,  ...,  0.0772,  0.1370,  0.0076],
         [ 0.0126, -0.0461, -0.0166,  ...,  0.0755,  0.1751,  0.0287],
         ...,
         [-0.0009, -0.0458,  0.0008,  ...,  0.0791,  0.1363,  0.0071],
         [-0.0030, -0.0640,  0.0005,  ...,  0.0662,  0.1623,  0.0338],
         [ 0.0040, -0.0584, -0.0054,  ...,  0.0804,  0.1635,  0.0176]],

        [[ 0.0169, -0.0913, -0.0146,  ...,  0.0778,  0.1655,  0.0162],
         [ 0.0036, -0.0858, -0.0125,  ...,  0.0838,  0.1564,  0.0172],
         [ 0.0087, -0.0730, -0.0316,  ...,  0.0786,  0.1705,  0.0228],
         ...,
         [ 0.0047, -0.0842, -0.0157,  ...,  0.0706,  0.1443,  0.0248],
         [ 0.0017, -0.0853,  0.0046,  ...,  0.0740,  0.1711,  0.0390],
         [ 0.0193, -0.0839, -0.0191,  ...,  0.0789,  0.1558,  0.0103]],

        [[ 0.0313, -0.0988, -0.0400,  ...,  0.0658,  0.1694,  0.0407],
         [ 0.0078, -0.1100, -0.0295,  ...,  0

In [17]:
class Conv(nn.Module):
    def __init__(self):
        super(Conv, self).__init__()
        self.conv1d = nn.Conv1d(100, 50, 2)

    def forward(self, x):
        return self.conv1d(x)

In [18]:
conv = Conv()
output = conv(x)

In [20]:
output.shape

torch.Size([8, 50, 9])

In [21]:
x.shape

torch.Size([8, 100, 10])