# Creating tensors

In [1]:
import torch
import numpy as np

In [2]:
my_tensor = torch.tensor([[0.0, 1.0], [0.1, 0.2]])
my_tensor

tensor([[0.0000, 1.0000],
        [0.1000, 0.2000]])

In [3]:
new_tensor = my_tensor.int().float()
new_tensor

tensor([[0., 1.],
        [0., 0.]])

In [4]:
np_tensor = np.array([[0.1, 1.0], [1.0, 0.2]])

In [5]:
tensor_from_np = torch.tensor(np_tensor)
tensor_from_np

tensor([[0.1000, 1.0000],
        [1.0000, 0.2000]], dtype=torch.float64)

In [6]:
to_numpy = tensor_from_np.numpy()
to_numpy

array([[0.1, 1. ],
       [1. , 0.2]])

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
my_tensor.to(device=device)

tensor([[0.0000, 1.0000],
        [0.1000, 0.2000]], device='cuda:0')

In [8]:
to_numpy = tensor_from_np.numpy()
to_numpy

array([[0.1, 1. ],
       [1. , 0.2]])

In [9]:
single_number = torch.tensor([0])
single_number

tensor([0])

In [10]:
single_number.item()

0

In [11]:
tensor_with_gradient = torch.tensor([[0.1, 1.0], [1.0, 2.0]], requires_grad=True)
result = tensor_with_gradient.pow(2).sum()
result.backward()
tensor_with_gradient.grad

tensor([[0.2000, 2.0000],
        [2.0000, 4.0000]])

In [12]:
tensor_with_gradient.detach_()

tensor([[0.1000, 1.0000],
        [1.0000, 2.0000]])

# Basic Operations

In [13]:
x = torch.tensor([[0.1, 1.0], [2.0, 1.0]])
x + 1

tensor([[1.1000, 2.0000],
        [3.0000, 2.0000]])

In [14]:
x * 2

tensor([[0.2000, 2.0000],
        [4.0000, 2.0000]])

In [15]:
y = torch.tensor([[0.1, 2.0], [2.0, 3.0]])
x + y

tensor([[0.2000, 3.0000],
        [4.0000, 4.0000]])

In [16]:
x[:, :]

tensor([[0.1000, 1.0000],
        [2.0000, 1.0000]])

In [17]:
x[1, :]

tensor([2., 1.])

In [18]:
x[:, 1]

tensor([1., 1.])

In [19]:
x = x.unsqueeze(0)

In [21]:
x.shape

torch.Size([1, 2, 2])

In [22]:
z = x + y
z

tensor([[[0.2000, 3.0000],
         [4.0000, 4.0000]]])

In [23]:
z.shape

torch.Size([1, 2, 2])

In [24]:
z = z.squeeze()
z

tensor([[0.2000, 3.0000],
        [4.0000, 4.0000]])

In [38]:
a = torch.arange(6).reshape(2, 3)

In [39]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

## 转置

In [40]:
torch.einsum("ij->ji", [a])

tensor([[0, 3],
        [1, 4],
        [2, 5]])

## 求和

$$ b = \sum_i \sum_j A_{ij} $$

In [41]:
a = torch.arange(6).reshape(2, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [42]:
torch.einsum("ij->", a)

tensor(15)

## 列求和（行维度不变，列维度消失）

$$ b_j = \sum_i A_{ij} $$

In [43]:
a = torch.arange(6).reshape(2, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [44]:
torch.einsum("ij->j", a)

tensor([3, 5, 7])

## 行求和（列维度不变，行维度消失）

$$ b_i = \sum_j A_{ij} $$

In [45]:
a = torch.arange(6).reshape(2, 3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [46]:
torch.einsum("ij->i", a)

tensor([ 3, 12])