In [1]:
a = [1.0, 2.0, 3.0, 4.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 1.0
a

[1.0, 2.0, 1.0, 4.0]

In [4]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [9]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
points = torch.tensor(
    [
        [4.0, 1.0],
        [5.0, 3.0],
        [2.0, 1.0],
    ]
)
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points = torch.tensor(
    [
        [4.0, 1.0],
        [5.0, 3.0],
        [2.0, 1.0],
    ]
)
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[0, 1]

tensor(1.)

In [16]:
points[0]

tensor([4., 1.])

In [17]:
points = torch.tensor(
    [
        [4.0, 1.0],
        [5.0, 3.0],
        [2.0, 1.0],
    ]
)
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [18]:
points_storage = points.storage()
points_storage[0]

4.0

In [19]:
points.storage()[1]

1.0

In [20]:
points = torch.tensor(
    [
        [4.0, 1.0],
        [5.0, 3.0],
        [2.0, 1.0],
    ]
)
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points = torch.tensor(
    [
        [4.0, 1.0, 4.0],
        [5.0, 3.0, 1.0],
        [2.0, 1.0, 4.0],
    ]
)
second_point = points[1]
second_point.storage_offset()

3

In [22]:
second_point.size()

torch.Size([3])

In [23]:
second_point.shape

torch.Size([3])

In [24]:
points.stride()

(3, 1)

In [25]:
second_point = points[2]
second_point.size()

torch.Size([3])

In [26]:
second_point.storage_offset()

6

In [27]:
second_point.stride()

(1,)

In [28]:
points = torch.tensor(
    [
        [4.0, 1.0],
        [5.0, 3.0],
        [2.0, 1.0],
    ]
)
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [29]:
points = torch.tensor(
    [
        [4.0, 1.0],
        [5.0, 3.0],
        [2.0, 1.0],
    ]
)
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [30]:
points = torch.tensor(
    [
        [4.0, 1.0],
        [5.0, 3.0],
        [2.0, 1.0],
    ]
)
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [31]:
points_t = points.t()

In [32]:
id(points.storage()) == id(points_t.storage())

False

In [33]:
points.stride()

(2, 1)

In [34]:
points_t.stride()

(1, 2)

In [35]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [36]:
transpose_t.shape

torch.Size([5, 4, 3])

In [38]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [44]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [45]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

In [48]:
a.shape

torch.Size([9])

In [50]:
a.storage_offset()

0

In [51]:
a.stride()

(1,)

In [52]:
b = a.view(3, 3)

In [53]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [55]:
id(a.storage()) == id(b.storage())

False

In [56]:
c = b[1:, 1:]

In [58]:
c.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

In [59]:
c.stride()

(3, 1)